project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "MATH 240"
  description: "Homepage for MATH 240 - Basic Statistics with R, Spring 2025."
  site-url: "https://jmochogi.github.io/basic-statwithR-sp25/"

  repo-url: https://github.com/jmochogi/basic-statwithR.git
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@jmochogi"
    image: "img/twitter-card.png"

  sidebar:
    background: "#11a9e6" 
    logo: "img/logo.jpeg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/jmochogi/basic-statwithR
        text: "GitHub repository"
      #- icon: code-square
       # href: https://cmgr.oit.duke.edu/containers
        #text: "RStudio containers"
      - icon: life-preserver
        href: https://calendly.com/jmochogi/20min
        text: "Office hours"
      - icon: chat-dots-fill
        href: https://canvas.ithaca.edu/
        text: "Canvas Discussions"
      - icon: camera-reels-fill
        href: https://ithaca.zoom.us/j/3364817575?pwd=WlA1S3hJWWZNTTFoWUVaZlA1clhtdz09
        text: "Zoom link"
      - icon: check-square-fill
        href: https://canvas.ithaca.edu/
        text: "Canvas"
        #menu:
         # - text: Gradescope
          #  url: https://canvas.duke.edu/courses/26106/external_tools/181
          #- text: Gradebook
           # url: https://canvas.duke.edu/courses/26106/gradebook

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          #- href: course-overview.qmd
           # text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
         # - href: course-team.qmd
          #  text: Teaching team
          - href: index.qmd
            text: Schedule
          #- href: course-links.qmd
            #text: Useful links
          - href: course-faq.qmd
            text: FAQ
      
      - section: "Labs"
        contents:
          - href: labs/Lab_1.qmd
            text: Lab 1
          - href: labs/Lab_2.qmd
            text: Lab 2
          - href: labs/Lab_3.qmd
            text: Lab 3
          - href: labs/Lab_4.qmd
            text: Lab 4            
          - href: labs/Lab_5.qmd
            text: Lab 5
          - href: labs/Lab_6.qmd
            text: Lab 6
          - href: labs/Lab_7.qmd
            text: Lab 7
            
            
     # - section: "Problem Posing"
      #  contents:
       #   - href: problem-posing/pp1.qmd
        #    text: Problem Posing 1
         # - href: problem-posing/pp2.qmd
          #  text: Problem Posing 2
            
      - section: "Projects"
        contents:
          #- href: project/first_project.qmd
           # text: Project 1
          - href: project/final_project.qmd
            text: Final Project
            
      #- section: "Problem Sets"
       # contents:
        #  - href: problem-sets/ps-1.qmd
         #   text: Problem Set 1
          #- href: problem-sets/ps-2.qmd
           # text: Problem Set 2
          #- href: problem-sets/ps_3.qmd
           # text: Problem Set 3
          #- href: problem-sets/ps-4.qmd
           # text: Problem Set 4 
            
            
      #- section: "Exam review"
       # contents:
        #  - href: exam-review/exam-1-review.qmd
         #   text: Exam 1
          #- href: exam-review/exam-2-review.qmd
           # text: Exam 2
      
      - section: "Downloads"
        contents:
          - href: course-downloads/datasets.qmd
            text: Datasets
          - href: course-downloads/templates.qmd
            text: Templates
  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2025, Joash Geteregechi"
    background: "#11a9e6" # Pantone Chambray Blue - Spring 2024, darkened to pass contrast checks

format:
  html:
    theme:
      light: [cosmo, style/math104.scss]
      dark: [cosmo, style/math104.scss, style/dark.scss]
    linkcolor: "#2d40c2"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-dark

execute:
  freeze: auto

editor: visual
